<?php

declare(strict_types=1);
ini_set('assert.exception','1');assert_options(ASSERT_ACTIVE,1);assert_options(ASSERT_EXCEPTION,1);
if(!function_exists('sanitize_text_field')){function sanitize_text_field(mixed $v):string{return trim(strip_tags((string)$v));}}
if(!function_exists('sanitize_textarea_field')){function sanitize_textarea_field(mixed $v):string{return trim(strip_tags((string)$v));}}
require_once dirname(__DIR__).'/src/Autoload.php';\Sabri\CF02\Autoload::register(dirname(__DIR__).'/src');

use Sabri\CF02\Infrastructure\WordPress\ApiInput;
use Sabri\CF02\Infrastructure\WordPress\RouteRegistrar;
use Sabri\CF02\Infrastructure\WordPress\SchemaCompletion;
use Sabri\CF02\Search\CursorCodec;
use Sabri\CF02\Security\DataCipher;
use Sabri\CF02\Security\ManagedKeyRing;
use Sabri\CF02\Feedback\SatisfactionAggregator;
use Sabri\CF02\Feedback\SatisfactionFeedback;
use Sabri\CF02\Domain\SupportCaseId;
use Sabri\CF02\Evidence\LegalHold;
use Sabri\CF02\Retention\PurgePlanner;
use Sabri\CF02\Retention\RetentionPolicy;

$root=dirname(__DIR__);$failures=[];$test=static function(int $round,string $name,callable $callback)use(&$failures):void{try{$callback();fwrite(STDOUT,sprintf("PASS REVIEW %02d %s\n",$round,$name));}catch(Throwable $e){$failures[]=sprintf('%02d %s: %s',$round,$name,$e->getMessage());fwrite(STDERR,sprintf("FAIL REVIEW %02d %s: %s\n",$round,$name,$e->getMessage()));}};$read=static fn(string $p):string=>(string)file_get_contents($root.'/'.$p);

$test(1,'staging and production activation gates are separated',static function()use($read):void{$s=$read('src/Activation/OperationalEvidenceRegistry.php');assert(str_contains($s,'CORE_REQUIRED'));assert(str_contains($s,'PRODUCTION_REQUIRED'));assert(str_contains($s, "$environment === 'production'"));});
$test(2,'activation binds approval to exact runtime identity',static function()use($read):void{$s=$read('src/Activation/ActivationGate.php');foreach(['runtime_version','schema_version','source_sha','package_sha256'] as $x)assert(str_contains($s,$x));assert(str_contains($s,'Founder approval does not target the exact artifact'));});
$test(3,'source and package hashes have distinct strict formats',static function()use($read):void{$s=$read('src/Activation/ActivationGate.php');assert(str_contains($s,"source_sha'=>'/^[a-f0-9]{40}$/"));assert(str_contains($s,"package_sha256'=>'/^[a-f0-9]{64}$/"));});
$test(4,'dependency health uses deterministic freshness and future checks',static function()use($read):void{$s=$read('src/Contracts/RequiredCompanionContracts.php');assert(str_contains($s,"modify('-15 minutes')"));assert(str_contains($s,"modify('+60 seconds')"));assert(!str_contains($s,'time()'));});
$test(5,'optional financial and clinical contracts activate only by condition',static function()use($read):void{$s=$read('src/Contracts/RequiredCompanionContracts.php');assert(str_contains($s,"'required'=>false"));assert(str_contains($s,'$definition[\'required\'] || $enabled'));});
$test(6,'File 00 assertion has no permissive fallback',static function()use($read):void{$s=$read('src/Authorization/WordPressPrincipalContextFactory.php');assert(str_contains($s, "($assertion['verified'] ?? false) !== true"));assert(!str_contains($s,'wp_get_current_user'));assert(!str_contains($s,'defaultAssertion'));});
$test(7,'File 00 assertion lists are bounded and format checked',static function()use($read):void{$s=$read('src/Authorization/WordPressPrincipalContextFactory.php');foreach(['32','256','64','count($value) > $maximum','preg_match($pattern'] as $x)assert(str_contains($s,$x));});
$test(8,'legacy duplicate controllers and surfaces are removed',static function()use($root):void{foreach(['src/Infrastructure/WordPress/RestController.php','src/Infrastructure/WordPress/AdminSurfaces.php','src/Infrastructure/WordPress/FrontendSurfaces.php'] as $p)assert(!is_file($root.'/'.$p),$p);});
$test(9,'local role removal records migration evidence and never grants authority',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/RoleRegistrar.php');assert(str_contains($s,'assigned_user_set_hash'));assert(str_contains($s,"file00_only"));assert(!str_contains($s,'add_role('));});
$test(10,'route contracts publish current schema 1.3',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/RouteRegistrar.php');assert(str_contains($s,'SchemaCompletion::VERSION'));assert(!str_contains($s,'SchemaExtension::VERSION'));});
$test(11,'route receipts require exact canonical set and versions independent of map order',static function():void{$receipts=[];foreach(RouteRegistrar::contracts() as $route=>$c){$receipts[$route]=['accepted'=>true,'owner'=>'File 20','module_version'=>'1.0.0-rc.5','schema_version'=>'1.3.0','contract_version'=>'1.1.0'];}if(!defined('CF02_VERSION'))define('CF02_VERSION','1.0.0-rc.5');$receipts=array_reverse($receipts,true);assert(RouteRegistrar::validateReceipts($receipts)===[]);unset($receipts[array_key_first($receipts)]);assert(RouteRegistrar::validateReceipts($receipts)!==[]);});
$test(12,'private route handling normalizes encoded and repeated slashes',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/Runtime.php');assert(str_contains($s,'rawurldecode'));assert(str_contains($s,"preg_replace('#/+#'"));assert(str_contains($s,'sanitize_key(wp_unslash'));
});
$test(13,'private surfaces send no-store anti-index and hardened browser headers',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/Runtime.php');foreach(['no-store','X-Robots-Tag','X-Frame-Options','Permissions-Policy','Content-Security-Policy','object-src \'none\''] as $x)assert(str_contains($s,$x));});
$test(14,'managed key provider is runtime and audience scoped',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/ManagedKeyRingProvider.php');assert(str_contains($s,"'audience'"));assert(str_contains($s,"'cf02-support-appeals'"));assert(str_contains($s,"'runtime_version'"));assert(str_contains($s,"'healthy'"));});
$test(15,'managed keys enforce active retired and revoked states',static function():void{$ring=new ManagedKeyRing('key2',['key2'=>['material'=>str_repeat('A',64),'status'=>'active'],'key1'=>['material'=>str_repeat('B',64),'status'=>'retired'],'key0'=>['material'=>str_repeat('C',64),'status'=>'revoked']],'Managed Provider','CF02-KEYROT-0001');assert($ring->material('key1')===str_repeat('B',64));$bad=false;try{$ring->material('key0');}catch(RuntimeException){$bad=true;}assert($bad);});
$test(16,'duplicate key material and multiple active keys are rejected',static function():void{$bad=false;try{new ManagedKeyRing('a01',['a01'=>['material'=>str_repeat('A',64),'status'=>'active'],'a02'=>['material'=>str_repeat('A',64),'status'=>'retired']],'Managed Provider','CF02-KEYROT-0002');}catch(RuntimeException){$bad=true;}assert($bad);});
$test(17,'retired key decrypts and re-encrypts under active key',static function():void{$old=new DataCipher(new ManagedKeyRing('old',['old'=>['material'=>str_repeat('O',64),'status'=>'active']],'Managed Provider','CF02-KEYROT-OLD1'));$ciphertext=$old->encrypt('rotation evidence');$ring=new ManagedKeyRing('new',['new'=>['material'=>str_repeat('N',64),'status'=>'active'],'old'=>['material'=>str_repeat('O',64),'status'=>'retired']],'Managed Provider','CF02-KEYROT-NEW1');$new=new DataCipher($ring);assert($new->decrypt($ciphertext)==='rotation evidence');assert(str_starts_with($new->rotate($ciphertext),'v2:new:'));});
$test(18,'key rotation batch is globally bounded concurrency-idempotent and records failures',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/EncryptionRotationService.php');assert(str_contains($s,'$remaining = $limit - $scanned'));assert(str_contains($s,"cf02_key_rotation_item_failed"));assert(str_contains($s,'SELECT {$cipherColumn} FROM {$table}'));assert(str_contains($s,"cf02_key_rotation_evidence_write_failed"));});
$test(19,'cursor base64 padding round trip is stable',static function():void{$c=new CursorCodec(str_repeat('S',64),1000);$v=$c->encode('case.scope',['updated_at'=>'2026-08-04 09:00:00','id'=>7],600);assert($c->decode($v,'case.scope')['id']===7);});
$test(20,'cursor tamper scope expiry and malformed positions fail closed',static function():void{$c=new CursorCodec(str_repeat('S',64),1000);$v=$c->encode('case.scope',['id'=>7],60);foreach([$v.'x',null] as $candidate){if($candidate===null)continue;$bad=false;try{$c->decode($candidate,'case.scope');}catch(Throwable){$bad=true;}assert($bad);}$bad=false;try{$c->decode($v,'other.scope');}catch(Throwable){$bad=true;}assert($bad);$late=new CursorCodec(str_repeat('S',64),1061);$bad=false;try{$late->decode($v,'case.scope');}catch(Throwable){$bad=true;}assert($bad);});
$test(21,'requester representation set is bound into cursor scope',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/CompleteRestOverlay.php');assert(str_contains($s,'wp_json_encode([$filters,$requesterRefs])'));assert(str_contains($s,'sort($refs)'));});
$test(22,'API errors are public-safe and private diagnostics use trace events',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/ComprehensiveRestController.php');assert(str_contains($s,'cf02_api_request_failed'));assert(str_contains($s,"The request was rejected. Review the fields"));assert(!str_contains($s,'$message = $error instanceof RuntimeException'));
});
$test(23,'canonical list APIs contain no offset pagination fallback',static function()use($read):void{$a=$read('src/Infrastructure/WordPress/ComprehensiveRestController.php');$b=$read('src/Infrastructure/WordPress/CompleteRestOverlay.php');assert(!str_contains($a,"get_param('offset')"));assert(!str_contains($b,"get_param('offset')"));assert(str_contains($b,"pagination'=>'opaque_keyset'"));});
$test(24,'requesters cannot self-assign P1/P2 severity authority',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/ComprehensiveRestController.php');$start=strpos($s,'public function createCase');$end=strpos($s,'public function getCase',$start);$block=substr($s,$start,$end-$start);assert(str_contains($block,'they never grant themselves P1/P2 authority'));assert(!str_contains($block,"get_param('priority')"));assert(!str_contains($block,"get_param('severity')"));});
$test(25,'idempotency mutation paths retain explicit keys and record versions',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/ComprehensiveRestController.php');assert(substr_count($s,'RequestGuard::idempotencyKey($request)')>20);assert(substr_count($s,'RequestGuard::expectedVersion($request)')>10);});
$test(26,'attachment creation requires explicit consent before metadata persistence',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/ComprehensiveRestController.php');$p=strpos($s,'Attachment consent is required');$q=strpos($s,'createAttachment(', $p);assert($p!==false&&$q!==false&&$p<$q);});
$test(27,'attachment upload grants require HTTPS validation and bounded expiry',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/ComprehensiveRestController.php');foreach(['wp_http_validate_url','https://','time() + 900','unsafe upload session'] as $x)assert(str_contains($s,$x));});
$test(28,'SLA and breach paths retain policy timers and observable events',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/RuntimeWorker.php');assert(str_contains($s,'SupportSlaAtRisk'));assert(str_contains($s,'SupportSlaBreached'));assert(str_contains($s,'processSla'));
});
$test(29,'temporary collaborator access expires and restricted scope requires approval',static function()use($read):void{$s=$read('src/Assignment/CaseAssignment.php');assert(str_contains($s, "$grant['expires_at'] <= $now"));assert(str_contains($s,'Restricted collaborator scope requires explicit purpose-bound approval'));
});
$test(30,'appeal evidence references are bounded sanitized unique and secret-safe',static function():void{$good=ApiInput::referenceList(['DECISION-1','EVIDENCE-2','DECISION-1']);assert($good===['DECISION-1','EVIDENCE-2']);$bad=false;try{ApiInput::referenceList(array_fill(0,26,'X'));}catch(RuntimeException){$bad=true;}assert($bad);});
$test(31,'feedback opt-out discards rating and encrypted comment at REST boundary',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/ComprehensiveRestController.php');assert(str_contains($s,'$optedOut || $comment ==='));$case=SupportCaseId::generate();$f=new SatisfactionFeedback($case,'person',null,null,true,new DateTimeImmutable());assert($f->optedOut());});
$test(32,'appeal reviewer assignment remains independent conflict and competence aware',static function()use($read):void{$s=$read('src/Appeal/ReviewerAssignmentPolicy.php');foreach(['wasInvolved','conflictsWith','hasCompetence','sensitiveClearance'] as $x)assert(str_contains($s,$x));});
$test(33,'native decision implementation remains reconciled against owner action object and version',static function()use($read):void{$s=$read('src/Integration/ImplementationReconciler.php');foreach(['observedOwner','observedAction','observedObjectReference','observedVersion','observedOutcomeReference'] as $x)assert(str_contains($s,$x));});
$test(34,'quality and satisfaction metrics enforce privacy cohort suppression',static function():void{$a=new SatisfactionAggregator();$case=SupportCaseId::generate();$items=[new SatisfactionFeedback($case,'a',5,null,false,new DateTimeImmutable()),new SatisfactionFeedback($case,'b',4,null,false,new DateTimeImmutable())];assert($a->aggregate($items,5)['suppressed']===true);});
$test(35,'active legal hold blocks destructive retention planning',static function():void{$case=SupportCaseId::generate();$at=new DateTimeImmutable('2026-08-04T00:00:00Z');$hold=LegalHold::forCase($case,'appeal_hold','authority',$at,$at->modify('+1 month'));$policy=new RetentionPolicy('technical',30,90,60,365,true);$plan=(new PurgePlanner())->plan($case,'technical','closed',$at->modify('-1 year'),$policy,[$hold],$at);assert($plan['action']==='hold');});
$test(36,'repair mutation requires dedicated capability recent auth and external approval evidence',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/RepairService.php');assert(str_contains($s,"hasCapability('repair.execute')"));assert(str_contains($s,'recentlyAuthenticated'));assert(str_contains($s,'cf02_repair_approval_evidence'));assert(!str_contains($s,"hasCapability('release.evidence.read')"));});
$test(37,'schema 1.3 contains repair and key-rotation ledgers',static function():void{$sql=SchemaCompletion::statements('wp_','DEFAULT CHARACTER SET utf8mb4');assert(SchemaCompletion::VERSION==='1.3.0');assert(isset($sql['key_rotation'],$sql['repair_ledger']));});
$test(38,'scheduler and uninstall both clear key rotation and all workers',static function()use($read):void{$s=$read('src/Infrastructure/WordPress/Scheduler.php').$read('uninstall.php');foreach(['cf02_process_outbox','cf02_process_events','cf02_process_sla','cf02_process_retention','cf02_process_reconciliation','cf02_process_key_rotation'] as $x)assert(substr_count($s,$x)>=2,$x);});
$test(39,'requester and admin surfaces contain complete governed journeys without browser-minted approval',static function()use($read):void{$front=$read('src/Infrastructure/WordPress/CompleteFrontendSurfaces.php').$read('assets/js/cf02-frontend.js').$read('assets/css/cf02-frontend.css');foreach(['subcategory','affected_object','consented','data-initial-case','data-initial-appeal'] as $x)assert(str_contains($front,$x));$admin=$read('src/Infrastructure/WordPress/CompleteAdminScript.php');assert(str_contains($admin,'Approved repair reference'));assert(!str_contains($admin,'crypto.randomUUID().replaceAll'));
});
$test(40,'release metadata is exact truthful and external gates remain separate',static function()use($root):void{$m=json_decode((string)file_get_contents($root.'/release/manifest.json'),true,512,JSON_THROW_ON_ERROR);assert($m['plugin_version']==='1.0.0-rc.6');assert($m['database_schema_version']==='1.3.0');assert($m['release_status']==='three-plan-harmonized-candidate-not-staging-accepted');assert(count($m['external_acceptance_gates'])>=8);});

if($failures!==[]){fwrite(STDERR,implode("\n",$failures)."\n");exit(1);}fwrite(STDOUT,"All forty CF-02 review/fix regressions passed.\n");