<?php

declare(strict_types=1);
ini_set('assert.exception','1');assert_options(ASSERT_ACTIVE,1);assert_options(ASSERT_EXCEPTION,1);
require_once dirname(__DIR__).'/src/Autoload.php';\Sabri\CF02\Autoload::register(dirname(__DIR__).'/src');
use Sabri\CF02\Appeal\ReviewerAssignmentPolicy;use Sabri\CF02\Appeal\ReviewerProfile;use Sabri\CF02\Governance\SupportParityAudit;use Sabri\CF02\Intake\GuestContinuationToken;use Sabri\CF02\Intake\GuestIntakePolicy;use Sabri\CF02\Safety\EmergencyRunbookRegistry;use Sabri\CF02\Delivery\OutcomeDeliveryGate;
$failures=[];$test=static function(string $n,callable $c)use(&$failures):void{try{$c();fwrite(STDOUT,"PASS {$n}\n");}catch(Throwable $e){$failures[]=$n.': '.$e->getMessage();fwrite(STDERR,"FAIL {$n}: {$e->getMessage()}\n");}};
$test('tampered and expired guest continuation tokens fail closed',static function():void{$now=new DateTimeImmutable('2026-09-08T00:00:00Z');$t=new GuestContinuationToken(str_repeat('x',SODIUM_CRYPTO_SECRETBOX_KEYBYTES));$token=$t->issue(['category'=>'technical'],$now,60);$tampered=substr($token,0,-1).($token[-1]==='A'?'B':'A');foreach([[$tampered,$now],[$token,$now->modify('+61 seconds')]] as [$candidate,$at]){$blocked=false;try{$t->verify($candidate,$at);}catch(Throwable){$blocked=true;}assert($blocked);}});
$test('guest channel rejects C3-C5 categories and prohibited secrets',static function():void{foreach([['category'=>'account_access','subject'=>'Account locked','description'=>'Need access'],['category'=>'technical','subject'=>'Password abcdef12345','description'=>'Please use OTP 123456']] as $input){$blocked=false;try{GuestIntakePolicy::normalize($input+['impact'=>'single_action','urgency'=>'normal','locale'=>'en-US']);}catch(Throwable){$blocked=true;}assert($blocked);}});
$test('same-unit or involved appeal reviewers are rejected',static function():void{$policy=new ReviewerAssignmentPolicy();$same=new ReviewerProfile('reviewer:same',['safety'],[],[],true,true,'safety_unit');$involved=new ReviewerProfile('reviewer:old',['safety'],['D-1'],[],true,true,'appeals_unit');$result=$policy->assign('D-1','actor:maker','safety',true,[$same,$involved],'safety_unit');assert($result['reviewer_reference']===null);});
$test('dead-letter outcome delivery can never authorize auto-close',static function():void{assert(OutcomeDeliveryGate::validate('dead_letter',true)!==[]);assert(OutcomeDeliveryGate::validate('queued',true)!==[]);assert(OutcomeDeliveryGate::validate('sent',true)===[]);});
$test('parity source rejects identity-bearing or unapproved aggregate keys',static function():void{$m=['first_response_seconds_p50'=>1,'resolution_seconds_p50'=>1,'escalation_rate'=>0.1,'reopen_rate'=>0.1,'appeal_access_rate'=>0.1];$blocked=false;try{(new SupportParityAudit())->evaluate('2026-08',['cohort_size'=>30,'metrics'=>$m,'user_ids'=>['u1']],['cohort_size'=>30,'metrics'=>$m]);}catch(InvalidArgumentException){$blocked=true;}assert($blocked);});
$test('emergency routing never claims ordinary SLA or automatic resolution',static function():void{foreach(EmergencyRunbookRegistry::types() as $type){$r=EmergencyRunbookRegistry::forType($type);assert(!$r['ordinary_sla']);assert(!$r['auto_close']);assert($r['owner']!=='');}});
if($failures!==[])exit(1);fwrite(STDOUT,"CF-02 C2-L Review 1 regressions passed.\n");
