<?php

declare(strict_types=1);
ini_set('assert.exception','1');assert_options(ASSERT_ACTIVE,1);assert_options(ASSERT_EXCEPTION,1);
$failures=[];$test=static function(string $n,callable $c)use(&$failures):void{try{$c();fwrite(STDOUT,"PASS {$n}\n");}catch(Throwable $e){$failures[]=$n.': '.$e->getMessage();fwrite(STDERR,"FAIL {$n}: {$e->getMessage()}\n");}};$root=dirname(__DIR__);
$test('release metadata is one exact rc6 candidate with schema 1.3',static function()use($root):void{$entry=file_get_contents($root.'/cf-02-support-appeals-case-management.php');$manifest=json_decode(file_get_contents($root.'/release/manifest.json'),true,512,JSON_THROW_ON_ERROR);$readme=file_get_contents($root.'/readme.txt');assert(str_contains($entry,'Version: 1.0.0-rc.6'));assert(str_contains($entry,"define('CF02_VERSION', '1.0.0-rc.6')"));assert($manifest['plugin_version']==='1.0.0-rc.6');assert($manifest['database_schema_version']==='1.3.0');assert(str_contains($readme,'Stable tag: 1.0.0-rc.6'));});
$test('stale rc2 candidate identity is removed from current release and staging docs',static function()use($root):void{foreach(['docs/RELEASE-PROCESS.md','docs/STAGING-ACCEPTANCE.md','docs/PRODUCTION-READINESS.md'] as $path){$text=file_get_contents($root.'/'.$path);assert(!str_contains($text,'Candidate version: `1.0.0-rc.2`'));assert(!str_contains($text,'Exact `1.0.0-rc.2`'));}});
$test('latest plan traceability names CEN-01 through CEN-10 and NJ-01 through NJ-06',static function()use($root):void{$text=file_get_contents($root.'/docs/TRACEABILITY.md');for($i=1;$i<=10;$i++){assert(str_contains($text,sprintf('CF02-CEN-%02d',$i)));}for($i=1;$i<=6;$i++){assert(str_contains($text,sprintf('CF02-NJ-%02d',$i)));}foreach(['AJ-09','AJ-10','AJ-18','AJ-20','AJ-24','AJ-25','AJ-34','AJ-35','AJ-36','AJ-38','AJ-39','AJ-40'] as $id){assert(str_contains($text,$id));}});
$test('CI and composer execute implementation plus two fresh C2-L reviews',static function()use($root):void{$ci=file_get_contents($root.'/.github/workflows/ci.yml');$composer=file_get_contents($root.'/composer.json');foreach(['c2l-latest-two-plans.php','c2l-review1.php','c2l-review2.php'] as $file){assert(str_contains($ci,$file));assert(str_contains($composer,$file));}});
$test('public repository contains only public-safe runbook metadata',static function()use($root):void{$text=file_get_contents($root.'/src/Safety/EmergencyRunbookRegistry.php');foreach(['password','private key','secret contact','incident credential'] as $forbidden){assert(!str_contains(strtolower($text),$forbidden));}});
if($failures!==[])exit(1);fwrite(STDOUT,"CF-02 C2-L fresh adversarial Review 2 passed.\n");
